# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
       with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "version-app" #Must be unique in Heroku
          heroku_email: "xrdikonimaki@hotmail.com"
