# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: onpush

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3 # download the repo
    - name: Use Node.js
      uses: actions/setup-node@v3 # set up node environment
      with:
        node-version: "16.x"
    - run: npm ci # install dependencies
    - run: npm test # run tests

  deploy:
    needs: build # build must have run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # download the repo
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}} # secret
          heroku_app_name: "version-app" #Must be unique in Heroku
          heroku_email: "xrdikonimaki@hotmail.com"
