on:
  workflow_run:
    workflows: ["Node.js"]
    types:
      - completed
name: Slack Notification
jobs:
   on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: '#B22222'
        SLACK_MESSAGE: ${{ github.event.workflow_run }}
        SLACK_ICON_EMOJI: '🐛'

